import type { Operation } from '@/types/operation'

const now = Date.now()
const hour = 60 * 60 * 1000
const day = 24 * hour

export const MOCK_OPERATIONS: Operation[] = [
  {
    id: 'operation-1',
    type: 'referral_reward',
    title: '+500 монет',
    description: 'Приглашён новый друг',
    amount: 500,
    currency: 'COINS',
    status: 'completed',
    createdAt: new Date(now - 2 * hour).toISOString(),
    icon: '🪙',
  },
  {
    id: 'operation-2',
    type: 'case_purchase',
    title: '-8 999 монет',
    description: 'Открытие Нищего кейса',
    amount: 8999,
    currency: 'COINS',
    status: 'completed',
    createdAt: new Date(now - 5 * hour).toISOString(),
    icon: '🎁',
  },
  {
    id: 'operation-3',
    type: 'case_reward',
    title: '+12 000 монет',
    description: 'Выигрыш в Нищем кейсе',
    amount: 12000,
    currency: 'COINS',
    status: 'completed',
    createdAt: new Date(now - 5 * hour - 30_000).toISOString(),
    icon: '🎉',
  },
  {
    id: 'operation-4',
    type: 'task_reward',
    title: '+2 000 монет',
    description: 'Задание: пригласи 3 друзей',
    amount: 2000,
    currency: 'COINS',
    status: 'completed',
    createdAt: new Date(now - day).toISOString(),
    icon: '✅',
  },
  {
    id: 'operation-5',
    type: 'order_purchase',
    title: '-34 999 монет',
    description: 'Покупка: Telegram Premium 6 месяцев',
    amount: 34999,
    currency: 'COINS',
    status: 'completed',
    createdAt: new Date(now - day - 3 * hour).toISOString(),
    icon: '🛒',
  },
  {
    id: 'operation-6',
    type: 'bonus',
    title: '+100 монет',
    description: 'Ежедневный бонус',
    amount: 100,
    currency: 'COINS',
    status: 'completed',
    createdAt: new Date(now - 2 * day).toISOString(),
    icon: '✨',
  },
  {
    id: 'operation-7',
    type: 'order_refund',
    title: '+1 000 монет',
    description: 'Возврат за заказ #1018',
    amount: 1000,
    currency: 'COINS',
    status: 'completed',
    createdAt: new Date(now - 3 * day).toISOString(),
    icon: '♻️',
  },
]
