export { Friends as FriendsPage } from './Friends'
export { GiveawayDetail as GiveawayDetailPage } from './GiveawayDetail'
export { Giveaways as GiveawaysPage } from './Giveaways'
export { Home as HomePage } from './Home'
export { NotFoundPage } from './NotFoundPage'
export { OperationsHistoryPage } from './OperationsHistoryPage'
export { OrdersPage } from './OrdersPage'
export { Profile as ProfilePage } from './Profile'
export { Shop as ShopPage } from './Shop'
export { Tasks as TasksPage } from './Tasks'
